# The URL the site will be built for
base_url = "https://pdddd.one"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "apollo"
title = "Patrik Drbal"
description = "My personal homepage"
generate_feeds = false
minify_html = true
taxonomies = [{ name = "tags" }]

[markdown]
external_links_target_blank = true
# highlight_code = true
# highlight_theme = "css"
# highlight_themes_css = [
#   { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
#   { theme = "ayu-light", filename = "syntax-theme-light.css" },
# ]

# [markdown.highlighting]
# theme = "catppuccin-mocha"

[extra]
use_cdn = false
#logo = "/images/favicon.png"
favicon = "/images/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/whaypr/hello/"

socials = [
    { name = "", url = "https://github.com/whaypr", icon = "github" },
    { name = "", url = "https://www.linkedin.com/in/patrik-drbal", icon = "linkedin" },
    { name = "", url = "mailto:patrik.drbal@fit.cvut.cz", icon = "email" },
    { name = "", url = "https://www.facebook.com/patrik.drbal", icon = "facebook" },
    { name = "", url = "https://www.instagram.com/drbalpat/", icon = "instagram" },
#    { name = "university", url = "https://fit.cvut.cz/en/faculty/people/23701-patrik-drbal", icon = "" },
]

menu = [
#    { name = "/posts", url = "/posts", weight = 1 },
#    { name = "/projects", url = "/projects", weight = 2 },
#    { name = "/talks", url = "/talks", weight = 3 },
#    { name = "/tags", url = "/tags", weight = 4 },
]

# See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14
